<?php

namespace AppBundle\Repository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    public function findActiveAdverts(){
        $em = $this->getEntityManager();
        $adverts = $em->createQuery(
            'SELECT a FROM AppBundle:Advert a
            WHERE CURRENT_TIMESTAMP() < a.date' )
        ->getResult();
        return $adverts;
    }   
    
}
